### ISSUE TITLE
no module names model

### ISSUE THREAD

**Issue by Yxt1212** [nobody-1617/DETA#1]
Hi.Thanks for your great work!
I meet a problem:"no module names model",is this module missing?

**Comment by JimZAI** [comment]
Could do you tell me, which file/line threw the Bug?

**Comment by nobody-1617** [comment]
Sorry for late response!

Could do you tell me, which file/line threw the Bug?

**Comment by Yxt1212** [comment]
Thank for your response. 
I follow your command
"python main.py --pretrained_model=MOCO --maxIt=40 --ratio=0. --test.type=10shot --ours --n_regions=2"
and the issue is <“/main.py", line 15, in <module> from models.losses import prototype_loss”>.
I found that other method like "TSA" or "URL" both have a folder with the name"models".

**Comment by nobody-1617** [comment]
Hi, 

Thanks for the heads up, I have re-uploaded the "models" folder. If any other questions follow, feel free to ask.
